# docker-compose.yml
version: "3"
services:
  pdc-api-swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8020:8080
    environment:
      - SWAGGER_JSON=/oas3/openapi.yaml
    volumes:
      - ./dist/:/oas3

  pdc-api-redoc:
    image: redocly/redoc
    ports:
      - 8025:80
    environment:
      - SPEC_URL=openapi.yaml
    volumes:
      - ./dist/openapi.yaml:/usr/share/nginx/html/openapi.yaml:ro

  ### If preferred or needed, uncomment the lines below to start the Swagger-editor
  ### Beware, the editor does not load the api-spec by default, nor saves it.
  ### In case of changes you need to manually commit changes to the source files
  # swagger-editor:
  #   image: swaggerapi/swagger-editor
  #   ports:
  #     - 8030:8080
  #   environment:
  #     - SWAGGER_FILE=/tmp/openapi.yaml
  #   volumes:
  #     - ./dist:/tmp
