openapi: 3.0.3
info:
  version: 0.1.0
  title: Producten- en Dienstencatalogus (PDC) API
  description: >-
    Een open standaard om PDC-synchronisatie tussen applicaties mogelijk te
    maken Omdat hier geen standaard voor is vanuit VNG-Realisatie of het
    Zorginstituut hebben enkele leveranciers (Stipter, Solviteers Software) hier
    zelf het initiatief toe genomen.
  license:
    name: European Union Public License, version 1.2 (EUPL-1.2)
    url: https://eupl.eu/1.2/nl/
paths:
  '/gemeenten/{gemeentecode}/producten':
    $ref: 'paths/gemeenten@{gemeentecode}@producten.yaml'
  '/gemeenten/{gemeentecode}/producten/{identificatie}':
    $ref: 'paths/gemeenten@{gemeentecode}@producten@{identificatie}.yaml'
  '/gemeenten/{gemeentecode}/producten/{identificatie}/aanbieders':
    $ref: 'paths/gemeenten@{gemeentecode}@producten@{identificatie}@aanbieders.yaml'
  '/gemeenten/{gemeentecode}/producten/{identificatie}/aanbieders{agbCode}':
    $ref: 'paths/gemeenten@{gemeentecode}@producten@{identificatie}@aanbieders@{agbCode}.yaml'
  '/gemeenten/{gemeentecode}/aanbieders':
    $ref: 'paths/gemeenten@{gemeentecode}@aanbieders.yaml'
  '/gemeenten/{gemeentecode}/aanbieders/{agbCode}':
    $ref: 'paths/gemeenten@{gemeentecode}@aanbieders@{agbCode}.yaml'
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      $ref: ./components/securitySchemes/bearerAuth.yaml

security:
  - bearerAuth: []
