type: object
description: Een product uit de PDC
properties:
  _links:
    $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/schemas/halCollectionLinks"
  identificatie:
    type: string
  naam:
    type: string
  typeWet:
    $ref: ./typeWet.yaml
  uitvoeringsvariant:
    $ref: ./uitvoeringsvariant.yaml
  financieringsvorm:
    $ref: ./financieringsvorm.yaml
  beginGeldigheid:
    type: string
    format: date
  eindeGeldigheid:
    type: string
    format: date
  vereistFiattering:
    type: string
    format: boolean
    default: false
  typeFiattering:
    type: array
    items:
      type: string
    description: Rollen die vereist zijn voor fiattering. Bijvoorbeeld collega, backoffice, manager
  toewijzingsvariant:
    oneOf:
      - $ref: ./toewijzingSpecifiek.yaml
      - $ref: ./toewijzingAspecifiek.yaml
      - $ref: ./toewijzingGeneriek.yaml
required:
  - identificatie
  - omschrijving
  - vereistFiattering
