type: object
description: Een product uit de PDC
properties:
  _links:
    $ref: ./override/halCollectionLinks.yaml
  identificatie:
    type: string
  naam:
    type: string
  omschrijving:
    type: string
  typeProduct:
    $ref: ./typeProduct.yaml
  typeWet:
    $ref: ./typeWet.yaml
  uitvoeringsvariant:
    $ref: ./uitvoeringsvariant.yaml
  financieringsvorm:
    $ref: ./financieringsvorm.yaml
  beginGeldigheid:
    type: string
    format: date
  eindeGeldigheid:
    type: string
    format: date
  vereistFiattering:
    type: boolean
    default: false
  typeFiattering:
    type: array
    items:
      type: string
    description: Rollen die vereist zijn voor fiattering. Bijvoorbeeld collega, backoffice, manager
  toewijzingsvariant:
    oneOf:
      - $ref: ./toewijzingSpecifiek.yaml
      - $ref: ./toewijzingAspecifiek.yaml
      - $ref: ./toewijzingGeneriek.yaml
  prijsRecords:
    type: array
    items:
      $ref: ./productPrijsRecords.yaml
  maxBudgetRecords:
    type: array
    items:
      $ref: ./maxBudget.yaml
required:
  - identificatie
  - omschrijving
  - vereistFiattering